### ISSUE TITLE
vscode (after 1.82.0) still not working under 1.1.0.1291

### ISSUE THREAD

**Issue by AgFlore** [vxiiduu/VxKex#126]
some logs left behind by vscode said that

```debug.log
[0316/114907.593:ERROR:critical_section_with_debug_info.cc (35)] InitializeCriticalSectionEx: 参数错误。(0x57)
```

```main.log
2024-03-16 16:55:01.174 [error] SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
at dt.Q (VsCode-win32-x64-1.87.2\resources\app\out\vs\code\electron-main\main.js:108:63512)
at dt.startup (main.js:108:55654)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Ee.a (main.js:110:1117)
```

vxl logs as attached
[kex_logs_1_82_0_and_1_87_2_and_1_88_0.zip](https://github.com/vxiiduu/VxKex/files/14623009/kex_logs_1_82_0_and_1_87_2_and_1_88_0.zip)

**Comment by jonm58** [comment]
do you "Enable VxKex for this program"?

**Comment by vxiiduu** [comment]
> The explorer shell property cannot persist, i checks the box, reenter, and the box is still not checked.

This sounds like it could be an issue with vxkex + whatever system configuration you have. In order to work around it, you can go to task scheduler, and confirm that "VxKex Configuration Elevation Task" is there.
![image](https://github.com/vxiiduu/VxKex/assets/73044267/795ec7df-6749-421f-b240-fb5231f4d4ba)
If it is there, try to right click and Run it.
![image](https://github.com/vxiiduu/VxKex/assets/73044267/6fba7ddd-e60c-438b-8cdb-a78c8123bccc)
You should see this dialog appear.
If all of these steps are followed and everything seems to be like what I described but the shell extension properties are still not working, you can *disable* the scheduled task. In this case, changing settings with the shell extension will now require a UAC dialog, but it may make it work.

**Comment by vxiiduu** [comment]
Alright. I will fix the InitializeCriticalSectionEx bug in the next release. There also looks like there is a problem with GetHostNameW (from Windows 8) which I will also fix in the next release.
![image](https://github.com/vxiiduu/VxKex/assets/73044267/986c1391-08e1-4b44-a752-e11434abdbdd)
![image](https://github.com/vxiiduu/VxKex/assets/73044267/ef71f379-748d-4c04-b73e-5651eb98bfe3)
Thanks for letting me know about this problem.

**Comment by vxiiduu** [comment]
With the release of 1.1.1.1375, VSCode and VSCodium are now working.

![image](https://github.com/vxiiduu/VxKex/assets/73044267/ae9d0551-a4bd-46f9-8c48-887f2cccd239)

Feel free to re-open the issue if there are still any problems.

**Comment by vxiiduu** [comment]
I installed 1.88 (Just as a side note, I used the portable zip) and cannot reproduce this bug. I've opened all my files and clicked everywhere you can click as well as minimize/maximize the window many times, but I cannot get the InitializeCriticalSectionEx problem to appear, and I can't get it to crash.

Since I cannot get the bug to happen, there is no solution for now. Sorry.

**Comment by vxiiduu** [comment]
Yeah actually that crash dump would help quite a lot. Now, I hope either Microsoft or Electron has published .pdb files that match VSCode, or otherwise it will be very hard to debug. Thanks for the efforts, I'll try my best.

**Comment by vxiiduu** [comment]
Alright, so it seems that **VSCode** does not have PDBs available. Do you mind trying to recreate the crash with **VSCodium** instead, since their PDBs are available on the Electron symbol server?

**Comment by vxiiduu** [comment]
That's fine, I should still be able to see what is going on without symbols. It will just take more time. And yes I see what you are talking about, VSCodium doesn't create a Crashpad folder.

**Comment by vxiiduu** [comment]
There is no need for you to spend more time investigating this issue. I found out what the problem is likely to be and I will post a debug build for you to try out after I fix the issue.

**Comment by vxiiduu** [comment]
Hi,
You can try this build and see if the problem goes away.

[KexSetup_Release.zip](https://github.com/vxiiduu/VxKex/files/14691909/KexSetup_Release.zip)

Your crash dump was extremely helpful. Thanks for uploading it.
